-- Contoh seeding minimal (opsional)
-- CREATE TABLE IF NOT EXISTS products (id SERIAL PRIMARY KEY, name TEXT NOT NULL);
-- INSERT INTO products (name) VALUES ('Sofa Minimalis'), ('Meja Kayu'), ('Kursi Rotan');
